### ISSUE TITLE
Can't use links in headers

### ISSUE THREAD

**Issue by joenoone** [mwesten/dokuwiki-plugin-header3#1]
Hi,
I have a page with several variations of the following markup which doesn't format properly : 
     ===[[RedHat| RedHat Related]]===

It displays (in bold):
      [[RedHat| RedHat Related]]

I'm running Release 2013-12-08 "Binky" and the only other plugin I've added is "mediasyntax".

**Comment by mwesten** [comment]
Closing this (unresolved) issue.
Dokuwiki Plugin Header:3 became unusable a long time ago, due to changes in Dokuwiki and in PHP.
I'm archiving this repo.
