### ISSUE TITLE
After upgrade to Hrun header2 and header3 don't work

### ISSUE THREAD

**Issue by nathfy** [mwesten/dokuwiki-plugin-header3#2]
Get the following in the error log:

using header3 as xhtml renderer 
PHP Fatal error:  Cannot access protected property renderer_plugin_header3::$node in /var/www/html/docuwiki/lib/plugins/header3/syntax.php on line 128, referer:

using header2 as xhtml renderer 
 PHP Fatal error:  Cannot access protected property renderer_plugin_header2::$node in /var/www/html/docuwiki/lib/plugins/header3/syntax.php on line 128

assume base class has changed, will post more if I find it...

**Comment by amazingBytes** [comment]
Yes, I can confirm this issue.
Do you have any further findings, yet?

**Comment by nathfy** [comment]
No time to look into it further, we've gone back to ponder stibbons for now.

**Comment by amazingBytes** [comment]
I've found one provisional solution that worked for me!

Change in DokuWiki's (2014-09-29a "Hrun") XHTML-Renderer /inc/parser/xhtml.php some methods from 'protected' to 'public':

Line 30: protected $sectionedits = array();
change to: public $sectionedits = array();

Line 43: protected $lastlevel = 0;
change to: public $lastlevel = 0;

Line 45: protected $node = array(0, 0, 0, 0, 0);
change to: public $node = array(0, 0, 0, 0, 0);

**Comment by amazingBytes** [comment]
Note: Please note my provisional solution ist still working for all newer Versions of DokuWiki

**Comment by Garretby** [comment]
Great solution, still work for me and latest version of wiki.

**Comment by amazingBytes** [comment]
My solution above is still working with DokuWiki release 2016-06-26 "Elenor of Tsort"

**Comment by amazingBytes** [comment]
... and with Release 2017-02-19b "Frusterick Manners", too!

**Comment by mwesten** [comment]
Closing this (unresolved) issue.
Dokuwiki Plugin Header:3 became unusable a long time ago, due to changes in Dokuwiki and in PHP.
I'm archiving this repo.
