### ISSUE TITLE
Doesn't work with PHP7

### ISSUE THREAD

**Issue by philtgun** [mwesten/dokuwiki-plugin-header3#4]
After installation, this plugin breaks the whole DocuWiki:
`PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /srv/wiki/lib/plugins/header3/syntax.php on line 46`

This behavior is one of the backwards incompatible changes, [link](http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.other.new-by-ref)

**Comment by amazingBytes** [comment]
Yes, can confirm this issue

**Comment by mwesten** [comment]
Closing this (unresolved) issue.
Dokuwiki Plugin Header:3 became unusable a long time ago, due to changes in Dokuwiki and in PHP.
I'm archiving this repo.
